import record from './record';
import { Replayer, type playerConfig, type PlayerMachineState, type SpeedMachineState } from './replay';
import canvasMutation from './replay/canvas';
import { _mirror } from './utils';
import * as utils from './utils';
export { EventType, IncrementalSource, MouseInteractions, ReplayerEvents, type eventWithTime, } from '@newrelic/rrweb-types';
import './replay/styles/style.css';
export type { recordOptions, ReplayPlugin } from './types';
declare const addCustomEvent: <T>(tag: string, payload: T) => void;
declare const freezePage: () => void;
declare const takeFullSnapshot: (isCheckout?: boolean | undefined) => void;
export { record, addCustomEvent, freezePage, takeFullSnapshot, Replayer, type playerConfig, type PlayerMachineState, type SpeedMachineState, canvasMutation, _mirror as mirror, utils, };
