language: node_js

os: linux

dist: focal

node_js:
  - lts/*

install:
  - yarn

script:
  - yarn build:all
  - yarn turbo run check-types
  - xvfb-run --server-args="-screen 0 1920x1080x24" yarn lerna run test
