packages:
  - 'packages/*'
  - 'packages/plugins/*'

allowBuilds:
  esbuild: true
  puppeteer: true
  spawn-sync: true
  svelte-preprocess: true

publicHoistPattern:
  - '*'

overrides:
  cssom: https://registry.npmjs.org/rrweb-cssom/-/rrweb-cssom-0.6.0.tgz
  '@types/dom-webcodecs': 0.1.5
  typescript: 5.4.5
