name: Bundle Stats

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout pull request head
        if: github.event_name == 'pull_request'
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Checkout current branch
        if: github.event_name != 'pull_request'
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Build bundle stats
        run: NODE_OPTIONS='--max-old-space-size=4096' yarn build:all
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
          RELATIVE_CI_STATS: 'true'
      - name: Upload bundle stats
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: relative-ci-stats
          path: packages/**/dist/webpack-stats.json
          if-no-files-found: error
