name: Tests

on: [push, pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Tests
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js lts/*
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_DOWNLOAD_BASE_URL: 'https://storage.googleapis.com/chrome-for-testing-public'

      - name: Build Project
        run: NODE_OPTIONS='--max-old-space-size=4096' yarn build:all

      - name: Check types
        run: yarn check-types

      - name: Run tests
        # run: PUPPETEER_EXECUTABLE_PATH=${{ steps.setup-chrome.outputs.chrome-path }} PUPPETEER_HEADLESS=true xvfb-run --server-args="-screen 0 1920x1080x24" yarn test
        run: PUPPETEER_HEADLESS=true xvfb-run --server-args="-screen 0 1920x1080x24" yarn test

      - name: Upload diff images to GitHub
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: image-diff
          path: packages/**/__image_snapshots__/__diff_output__/*.png
          if-no-files-found: ignore
