name: ESLint Check

on:
  push:
  pull_request:

jobs:
  eslint_check_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: ESLint Check and Report Upload

    steps:
      - name: Checkout pull request head
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout current branch
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Build Packages
        run: NODE_OPTIONS='--max-old-space-size=4096' yarn build:all
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
          RELATIVE_CI_STATS: 'true'
      - name: Eslint Check
        run: yarn turbo run lint
      - name: Save Code Linting Report JSON
        run: yarn lint:report
        # Continue to the next step even if this fails
        continue-on-error: true
      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        with:
          name: eslint_report.json
          path: eslint_report.json

      - name: Upload bundle stats
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: relative-ci-stats
          path: packages/**/dist/webpack-stats.json
          if-no-files-found: error
