name: Prerelease

on:
  workflow_dispatch:
    inputs:
      dist-tag:
        description: 'npm dist-tag to publish under'
        required: true
        default: 'alpha'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js 24.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      - name: Exit pre mode (required for snapshot releases)
        run: yarn changeset pre exit || true

      - name: Generate snapshot versions
        run: yarn changeset version --snapshot ${{ inputs.dist-tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build packages
        run: yarn build:all
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Publish snapshot to npm
        run: node_modules/.bin/changeset publish --tag ${{ inputs.dist-tag }} --no-git-tags
        env:
          NPM_CONFIG_PROVENANCE: 'true'
