name: Release

on:
  push:
    branches:
      - master
      - alpha

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 24.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      - name: Build packages
        run: yarn build:all
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: 'true'
