name: Code Style Check

on:
  push:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  eslint_check_upload:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: ESLint Check and Report Upload

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Build Packages
        run: NODE_OPTIONS='--max-old-space-size=4096' yarn build:all
      - name: Eslint Check
        run: yarn turbo run lint
      - name: Save Code Linting Report JSON
        run: yarn lint:report
        # Continue to the next step even if this fails
        continue-on-error: true
      - name: Upload ESLint Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: eslint_report.json
          path: eslint_report.json

  prettier_check:
    # In the forked PR, it's hard to format code and push to the branch directly, so the action only checks the format correctness.
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    permissions:
      contents: read
    runs-on: ubuntu-latest
    name: Format Check
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Prettier Check
        run: yarn prettier --check '**/*.{ts,md}'

  prettier:
    # Skip the format code action in forked PRs
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Format Code
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Prettify Code
        run: yarn prettier --write '**/*.{ts,md}'
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
          file_pattern: ':!packages/rrweb-player/.svelte-kit/ambient.d.ts'
