name: Code Style Check

on: [push, pull_request_target]

jobs:
  eslint_check_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: ESLint Check and Report Upload

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Build Packages
        run: NODE_OPTIONS='--max-old-space-size=4096' yarn build:all
      - name: Eslint Check
        run: yarn turbo run lint
      - name: Save Code Linting Report JSON
        run: yarn lint:report
        # Continue to the next step even if this fails
        continue-on-error: true
      - name: Upload ESLint Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: eslint_report.json
          path: eslint_report.json

  annotation:
    # Skip the annotation action in push events
    if: github.event_name == 'pull_request_target'
    permissions:
      checks: write
    needs: eslint_check_upload
    runs-on: ubuntu-latest
    name: ESLint Annotation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: eslint_report.json
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@5f4dc2e3af8d3c21b727edb597e5503510b1dc9c # v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'

  prettier_check:
    # In the forked PR, it's hard to format code and push to the branch directly, so the action only check the format correctness.
    if: github.event_name != 'push' && github.event.pull_request.head.repo.full_name != 'rrweb-io/rrweb'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    name: Format Check
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Prettier Check
        run: yarn prettier --check '**/*.{ts,md}'

  prettier:
    # Skip the format code action in forked PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == 'rrweb-io/rrweb'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Format Code
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Prettify Code
        run: yarn prettier --write '**/*.{ts,md}'
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
          file_pattern: ':!packages/rrweb-player/.svelte-kit/ambient.d.ts'
